percy/percy-selenium-js

index.js, package.json
Follows a similar pattern as other SDKs without explicit URL fetching
Also updated repository field in package.json
=> ♻️ Gather document URL from within script execution

README.md
This removes yarn install instructions & adds upgrading instructions (with `@percy/migrate`)
=> 📝  Prepare README for release

package.json, yarn.lock
Even though they're loosely set (and should resolve to the latest anyways), it's not a bad idea to force it the latest for this upcoming release.
=> ⬆️ Bump @percy dependencies to latest

index.js, test/index.test.mjs
Implementing Ignore Region for different types including ignore by id, xpath, selenium webelement and custom ignore region for POA.
=> POA Support for ignoreRegion

.github/workflows/Semgrep.yml, index.js
Import Statement was breaking for some reason when making it work with PoA CLI changes.
=> Pplt 2059 fix 1

package.json
=> 🔖  v2.0.0-beta.0

index.js, test/index.test.mjs
Send consider region elements to CLI
=> Add consider regions

package.json
Release percy-selenium-js - `v2.0.0`
=> :bookmark: release v2.0.0 js-selenium-sdk

package.json
=> :bookmark: release-v2.0.1-beta.1

README.md, package.json
=> :bookmark: release-v2.0.1

README.md
- Updating ReadMe for PoA FullPage
=> 📝  PoA Full Page Support

index.js, package-lock.json, package.json, types/index.d.ts, types/index.test-d.ts
Removed selenium-webdriver from peer-dependency, 
added percyScreenshot method in types,
=> Removed selenium webdriver as a peer dependency

README.md, package.json
:bookmark: `release 2.0.4-beta.0`
- Support for `sync` keyword
=> :bookmark: release-v2.0.4-beta.0

package.json
:bookmark: release-v2.0.4-beta.0-change-tag to beta
=> :bookmark: release-v2.0.4-beta.0-change-tag to beta

package.json
=> :bookmark: v2.0.4

package.json
=> 🔖 release 2.1.0-beta.0

index.js, test/index.test.mjs
- Feat: Throw Error if PERCY_RAISE_ERROR is True
=> Feat: Throw Error if PERCY_RAISE_ERROR is True

package.json
=> :bookmark: v2.2.1-beta.0

README.md, index.js, package.json, test/index.test.mjs, yarn.lock
adding region changes - helper function, readme, tests
updated cli to 1.30.9
=> adding regions support for sdk

package.json
=> 🔖 Release v2.2.3-beta.0

package.json
=> 🔖 Release v2.2.3
